server:
  port: 8080

  servlet:
    session:
      timeout: 3600s

spring:
  data:
    mongodb:
#      uri: mongodb://localhost:27017//user?directConnection=true
      host: localhost
      port: 27017
      database: user
      username: liftyun
      password: liftyun
#      authentication-database: admin
  thymeleaf:
    cache: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration